/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/exception/403.vue')['default']
    404: typeof import('./src/components/exception/404.vue')['default']
    500: typeof import('./src/components/exception/500.vue')['default']
    Buttons: typeof import('./src/components/exception/buttons.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KevyEmpty: typeof import('./src/components/kevy-empty/components/kevy-empty/kevy-empty.vue')['default']
    Navbar: typeof import('./src/components/layout/Navbar.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTable: typeof import('@nutui/nutui-taro')['Table']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    Router: typeof import('./src/components/layout/Router.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/layout/TabBar.vue')['default']
  }
}
